### ISSUE TITLE
Error with Browse while setting up sugar-build on Ubuntu 14.04

### ISSUE THREAD

**Issue by iamutkarshtiwari** [sugarlabs/sugar-build#39]
I was trying to setup the sugar-build by following the procedure mentioned on dev-envionment.md when I faced this error -> https://gist.github.com/iamutkarshtiwari/0026eff4f4e5886acf6bf2685e9bec2b

This issues happens to appear when the setup tries to 'build' the Browse activity from the pulled code.
To solve this issues, I had to replace the 'browse' folder in the 'sugar-build/' directory with an older version of Browse.

**Comment by samdroid-apps** [comment]
You need to update sugar-toolkit-gtk3 so it has this:  https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/298
