### ISSUE TITLE
xorg-x11-drv-vmmouse has been retired from f25

### ISSUE THREAD

**Issue by i5o** [sugarlabs/sugar-build#42]
In sugar-build/build/root.json the package xorg-x11-drv-vmmouse is present, making the installation in fedora25 not possible.

Removing it from root.json fixes the problem.

The point is, is that package really important, or we can just remove it?

**Comment by Hrishi1999** [comment]
After removing it, how can I test it? (I am a GCI contestant here, and I am not much experienced with all this).

**Comment by i5o** [comment]
Hello @Hrishi1999 ,  by test I mean: Use sugar with the package, then remove it, do you notice any difference, does it still works as before (with the package not-installed)

Welcome to GCI :)

**Comment by Hrishi1999** [comment]
Thanks for the quick reply. So, how can i use sugar with the package? Just give me a brief idea and I might be good to go :)

**Comment by i5o** [comment]
Well, you first need to build sugar-build with the package installed and test, then re-build it with the package not installed (you may want to look in root.json file!).

Just to let you know,, i'm using fedora 25.

**Comment by Hrishi1999** [comment]
Hello, I am running Ubuntu over Windows in VMware. Now, I have cloned sugar-build.git, pulled it, build it, and ran. It ran at first. Now after, I removed the "xorg-x11-drv-vmmouse" from root.json, it doesn't pull, build or run anymore. It is giving me too many errors. I am doing everything correct. Please help me.
