### ISSUE TITLE
Can't pull in fedora 25.

### ISSUE THREAD

**Issue by Hrishi1999** [sugarlabs/sugar-build#44]
after cloning sugar-build.git, if you will try "./osbuild pull" you will probably receive in error. I think this might happen because of incompatibility issues with f25.

**Comment by tradzik** [comment]
What is an error message?

**Comment by Hrishi1999** [comment]
Sorry for not writing this issue properly. Now, if you try to pull, you will get output errors in osbuild. I was trying to remove that vmmouse dependency, but failed too because I can't test it. In short, I will post output on fpast.org soon, again.

**Comment by Hrishi1999** [comment]
https://paste.fedoraproject.org/494751/

**Comment by i5o** [comment]
The dependency error has been fixed. We need to take a look about sugar-web: see https://github.com/sugarlabs/sugar-build/issues/43
