### ISSUE TITLE
build issues 

### ISSUE THREAD

**Issue by Becram** [sugarlabs/sugar-build#52]
why am I having this problem in Ubuntu 17.04.Please help @iamutkarshtiwari. I have followed this https://developer.sugarlabs.org/dev-environment.md.html

> Command failed: python2.7 /home/broot/sugar-build/browse/setup.py install --prefix /home/broot/sugar-build/build/out/install
> 
> Traceback (most recent call last):
>   File "/home/broot/sugar-build/browse/setup.py", line 21, in <module>
>     bundlebuilder.start()
>   File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/sugar3/activity/bundlebuilder.py", line 629, in start
>     globals()['cmd_' + options.command](config, options)
>   File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/sugar3/activity/bundlebuilder.py", line 509, in cmd_install
>     installer.install(options.prefix, options.install_mime, options.install_desktop_file)
>   File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/sugar3/activity/bundlebuilder.py", line 282, in install
>     self.builder.build()
>   File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/sugar3/activity/bundlebuilder.py", line 125, in build
>     self.build_locale()
>   File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/sugar3/activity/bundlebuilder.py", line 157, in build_locale
>     cat = gettext.GNUTranslations(open(mo_file, 'r'))
>   File "/usr/lib64/python2.7/gettext.py", line 180, in __init__
>     self._parse(fp)
>   File "/usr/lib64/python2.7/gettext.py", line 317, in _parse
>     self.plural = c2py(plural)
>   File "/usr/lib64/python2.7/gettext.py", line 93, in c2py
>     raise ValueError, 'plural forms expression could be dangerous'
> ValueError: plural forms expression could be dangerous

**Comment by quozl** [comment]
That's obviously not a problem with `sugar-build`, but a problem in `Browse`.

Fixed by https://github.com/sugarlabs/browse-activity/commit/eb180fef785b2c396334feea9b972021de1dfe18

Please, don't use `sugar-build` unless you're a python developer and can read a traceback.  `sugar-build` is far too fragile, and will fail if any of the dependencies fail.
